### ISSUE TITLE
How to install it in XAMPP in Windows? please I'm beginner

### ISSUE THREAD

**Issue by anddizza** [Humbedooh/server-status#10]
I already install Lua for Windows, but how to do the settings in XAMPP Apache? please I want to integrate this graphical data on the server status in XAMPP

**Comment by JBlond** [comment]
Enable mod lua and add the lua handler
```xml
LoadModule lua_module modules/mod_lua.so

AddHandler lua-script .lua
```

You can also use the LuaMapHandler 

Please refer to the https://github.com/Humbedooh/server-status/blob/master/README.md
