### ISSUE TITLE
Get remote server informations

### ISSUE THREAD

**Issue by wixaw** [Humbedooh/server-status#5]
Hello,
I would make a dashboard for multiple web server.
How can I query the "/server-status" of a remote server?

I modify "host = r.server_name"  to "host = xx.xx.xx.xx" but not work.

Thanks in advance !

**Comment by Humbedooh** [comment]
Is your aim to combine the metrics, or display one chart per server?
I would think you would make a static page somewhere that queries both servers (assuming it's https on all machines)

**Comment by wixaw** [comment]
Sorry I use now ElasticStack
