### ISSUE TITLE
 x-forwarded for header data 

### ISSUE THREAD

**Issue by L-walton** [Humbedooh/server-status#6]
I'd love if I could get x-forwarded for header info as one of the fields in 
`/server-status?view=json&extended=true`
Not sure if this is possible, it would be very valuable to me.

**Comment by L-walton** [comment]
Looking in the lua module, 
`headers_in | table | yes | MIME header environment from the request. This contains headers such as Host, User-Agent, Referer and so on.`

`forwardedip = r.headers_in['X-Forwarded-For']`

Looking at the existing code, I see an example 
`vhost = worker.vhost:gsub(":%d+", ""),`
Is vhost in headers_in?

**Comment by Humbedooh** [comment]
I don't think that information is available in the scoreboard, sorry.
https://ci.apache.org/projects/httpd/trunk/doxygen/scoreboard_8h_source.html explains what's available in it. Adding x-forwarded-for is technically possible, but it would require adding a handler for each request that sets a note or some such, and then somehow massage that into the scoreboard. This could be done via the IVM features I think, but it's beyond the scope of this application at the moment.
