### ISSUE TITLE
Prometheus metrics?

### ISSUE THREAD

**Issue by eightnoneone** [Humbedooh/server-status#7]
I realize this is a project from long ago, but ever consider having it do Prometheus metrics?

**Comment by JBlond** [comment]
I wonder why you want to have a complete monitoring tool into the server status page? Even though this is newer than the plain server-status page, but in lua, it is just the apache status page.

**Comment by eightnoneone** [comment]
I’m looking to have a more native export of Prometheus metrics than the existing Go server-status scripts running another listener. This seemed like a related capability. The existing page output is interesting, but only a tangent to my needs.
